### PR TITLE
Debian Packaging

### PR DESCRIPTION
**Pull request by Vitexus**
My initial version of Debian packagaing #84

### CODE REVIEW

**Comment by CrazySpence** [comment]
Dont entirely understand how that process works but none of these changes affected the game so i'll merge it in.

**Comment by Vitexus** [comment]
Cool @CrazySpence ! now we must test it deeply. I did not fix problems yet. But now in origin repository is there hope that someone with bigger skills help us to make packages worl properly.

**Comment by Vitexus** [comment]
> Yea not sure how deeply i can help with that, not sure what to even do with that folder you added.

Ok, i can add short howto into readme how to build debian/ubuntu package. Please stay tuned.

**Comment by CrazySpence** [comment]
Sounds good to me, not opposed to learning just currently don't know how.

**Pull request merged**
